I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapter_2.rpy", line 131, in script
    scene ferris_wheel with flash
  File "game/chapter_2.rpy", line 131, in <module>
    scene ferris_wheel with flash
NameError: name 'flash' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapter_2.rpy", line 131, in script
    scene ferris_wheel with flash
  File "/Users/enikfeirgraw/Applications/renpy-6.99.11-sdk/renpy/ast.py", line 1271, in execute
    paired = renpy.python.py_eval(self.paired)
  File "/Users/enikfeirgraw/Applications/renpy-6.99.11-sdk/renpy/python.py", line 1725, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Users/enikfeirgraw/Applications/renpy-6.99.11-sdk/renpy/python.py", line 1719, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/chapter_2.rpy", line 131, in <module>
    scene ferris_wheel with flash
NameError: name 'flash' is not defined

Darwin-16.5.0-x86_64-i386-64bit
Ren'Py 6.99.12.2.2029
WIP2 0.04
